#! /usr/bin/env ruby

require 'pg'
require 'io/console'

class ExpenseData
  def initialize
    self.connection = PG.connect(dbname: "expenses")
  end

  def list_expenses
    result = connection.exec("SELECT * FROM expenses ORDER BY created_on ASC;")
    show(result)
  end

  def add_expense(amount, memo)
    sql = "INSERT INTO expenses(amount, memo, created_on) " \
          "VALUES ($1, $2, NOW());"
    connection.exec_params(sql, [amount, memo])
  end

  def search_expenses(term)
    sql = "SELECT * FROM expenses WHERE memo ILIKE $1;"
    result = connection.exec_params(sql, ["%#{term}%"])
    show(result)
  end

  def delete_expense(id)
    sql_selection = "SELECT * FROM expenses WHERE id = $1;"
    result = connection.exec_params(sql_selection, [id])
    abort "There is no expense with the id '#{id}'" if result.ntuples.zero?
    sql_deletion = "DELETE FROM expenses WHERE id = $1;"
    connection.exec_params(sql_deletion, [id])
    puts 'The following expense has been deleted:'
    show(result)
  end

  def delete_all_expenses
    connection.exec("DELETE FROM expenses;")
    puts 'All expenses have been deleted.'
  end

  protected
  attr_accessor :connection

  def show(result)
    tuples_count = result.ntuples
    abort 'There are no expenses.' if tuples_count.zero?
    puts "There are #{tuples_count} expense#{'s' if count != 1}"
    result.each do |item|
      puts " #{item["id"].rjust(3)} | #{item["created_on"]} |#{item["amount"].rjust(12)}" \
           " | #{item["memo"]}"
    end
    show_total(result)
  end

  def show_total(result)
    total = result.field_values('amount').map(&:to_f).sum.round(2).to_s
    puts '-' * 50
    puts  "Total" + "#{total.rjust(26)}"    
  end
end

class CLI
  def initialize
    self.expense_app = ExpenseData.new
  end

  def display_help
    <<~HELP_INFO
      An expense recording system

      Commands:

      add AMOUNT MEMO [DATE] - record a new expense
      clear - delete all expenses
      list - list all expenses
      delete NUMBER - remove expense with id NUMBER
      search QUERY - list expenses with a matching memo field
    HELP_INFO
  end

  def add_arguments_present?(cli_args)
    return false if cli_args[1].nil? || cli_args[2].nil?
    true
  end

  def second_argument_present?(cli_args)
    return false if cli_args[1].nil?
    true
  end

  def run(cli_args)
    command = cli_args[0]
    case command
    when 'list'
      expense_app.list_expenses
    when 'add'
      abort 'You must provide an amount and memo.' unless add_arguments_present?(cli_args)
      amount = cli_args[1]
      memo = cli_args[2]
      expense_app.add_expense(amount, memo)
    when 'search'
      abort 'You must provide a search term' unless second_argument_present?(cli_args)
      term = cli_args[1]
      expense_app.search_expenses(term)
    when 'delete'
      abort 'You must provide an expense id' unless second_argument_present?(cli_args)
      id = cli_args[1]
      expense_app.delete_expense(id)
    when 'clear'
      puts 'This will remove all expenses. Are you sure? (y/n)'
      verification = $stdin.getch
      return unless verification.match?(/^y/i)
      expense_app.delete_all_expenses
    else
      puts display_help
    end
  end

  protected
  attr_accessor :expense_app
end

CLI.new.run(ARGV)
